export const UPDATE_PLAN_DETAILS = 'UPDATE_PLAN_DETAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_STEP = 'UPDATE_STEP';
export const UPDATE_DEDUCTIBLE_DECLARATION = 'UPDATE_DEDUCTIBLE_DECLARATION';
export const UPDATE_DECLARATION= 'UPDATE_DECLARATION';
export const UPDATE_DEDUCTIBLE_AMOUNT = 'UPDATE_DEDUCTIBLE_AMOUNT';